services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: share_3d_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/share_3d_development
      # RAILS_MASTER_KEY: # Указать в .env или при запуске
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    # Run tailwind watcher in background and then Rails server
    command: bash -lc "bundle exec rails db:prepare && bin/rails tailwindcss:watch & bundle exec rails server -b 0.0.0.0 -p 3000"

volumes:
  db_data:
